### ISSUE TITLE
Issues running the simmechanics-to-urdf

### ISSUE THREAD

**Issue by ezeob002** [robotology/simmechanics-to-urdf#10]
I followed all the steps provided in the page below https://github.com/robotology/simmechanics-to-urdf#debianubutu. I tried the following commands in the directory containing my .xml file but i got the following output
Input

`simmechanics_to_urdf {SimMechanics XML Robot_1_Assembly} --yaml [yaml_configfile] --csv-joint csv_joints_configfile --output {xml|graph|none}`

Output
~~~
one}: command not found
usage: simmechanics_to_urdf [-h] [--csv-joints [CSV_JOINTS_CONFIG]]
                            [--yaml [YAML_CONFIG]] [--output [MODE]]
                            [--outputfile [OUTPUTFILE_NAME]]
                            [filename]
simmechanics_to_urdf: error: unrecognized arguments: XML Robot_1_Assembly}
graph: identical upper and lower x limits are separated
graph: identical upper and lower y limits are separated
~~~

I downloaded the simmechanic-to-urdf and urdform in a my home directory, I also tried putting them in my catskin_ws folder but it was not working. I am using ROS indigo package in ubuntu 14.04. I also tried to include the following in my catkin_ws/src CMakelist  

catkin_install_python(PROGRAMS scripts/install
                      DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})

and 

catkin_python_setup()

but I still got an compilation problem.

Please I will appreciate any suggestions or hint on how to use these package.

Thanks

**Comment by traversaro** [comment]
Ok, one thing at a time: 
 * The script runs, so the installation was successful. 
 * `simmechanics-to-urdf` is a plain python package, so it does not have anything to do with catkin.  

The script gives you an error because while executing the script you should substitute `{SimMechanics XML Robot_1_Assembly}` with the name of your simmechanics xml file , `[yaml_configfile]` with the name of your yaml configuration file, and `csv_joints_configfile` with the name of your csv configuration file, and `{xml|graph|none}` with the selected output. 
As a first test you can simply try: 
~~~
simmechanics-to-urdf nameOfYourSimmechanicsFile.xml --output xml --outputfile yourRobot.urdf
~~~

**Comment by ezeob002** [comment]
Thanks for the reply I really appreciate it. I tried the following command:

simmechanics-to-urdf Robot_1_Assembly.xml --output xml --outputfile yourRobot.urdf

I created an empty file named yourRobot.urdf and I got the following error:

simmechanics-to-urdf: command not found

Do I need to run the command in the folder where I installed simmechanics-to-urdf?

I don't have a yaml config file.

Thanks

**Comment by traversaro** [comment]
Sorry the command is with underscore, my error.

**Comment by ezeob002** [comment]
Thanks it works now

**Comment by traversaro** [comment]
OK, let me know if YouTube have further issues with the generated model.

**Comment by traversaro** [comment]
@ezeob002 closing the issue because the problem was solved, feel free to reopen if you have any new issue.
