### ISSUE TITLE
Frame parameters in configuration file

### ISSUE THREAD

**Issue by nskw** [robotology/simmechanics-to-urdf#13]
I tried to create configuration file of my robot by mimicking test/legs_simmechanics_options.yaml.
But, my XML file from Creo has no displayName. 
<displayName>""</displayName> 

How can I insert this name?

**Comment by nskw** [comment]
And, I am not sure each function of Link Frames Parameters and Exported Frame Parameters. 
Is it correct that Link Frames Parameters are for sensors, and Exported Frame Parameters are for the contact to the environment?

**Comment by traversaro** [comment]
Hi @nskw ,

What do you mean by "my XML file from Creo has no displayName"? The displayName is tag present on some simmechanics frames, I actually don't know when it is added and when it is not added, but as far I could see it is added to the frames that are explicitly exported from CAD (as explained in https://www.icub.org/wiki/Creo_Mechanism_to_URDF#Add_additional_reference_frames ). 

If you don't tick the "Export oncy CSs with this prefix` option on the settings dialog for SimMechanics Link, then I think you don't have any frame with the `displayName` setted.

**Comment by traversaro** [comment]
The `linkFrames` option is used to try to assign the frame of a link to a  frame present in the SimMechanics file. It identifies the frame with the `displayName` option because the usual workflow is: as we don't know which kind of link frames SimMechanics Link exports from the model, we explicitly export some frames using the `Export oncy CSs with this prefix` option, and then we assign this frames to be the be the link frame using the `linkFrames` option in the `simmehcanics-to-urdf` script. 

The exportedFrames options is instead use to export **additional** frames that are not the frame of a link. As the URDF does not distinguish the concept of frame from the concept of link, this additional frames are added as "fake" links with 0 mass and connected with a "fixed" joint with the real link.
