### ISSUE TITLE
How to include the ft sensor into sdf file 

### ISSUE THREAD

**Issue by nskw** [robotology/simmechanics-to-urdf#15]
We made urdf file using simmechanics-to-urdf. 
And, we converted it to sdf file using gz command. 
However, sdf file has no ft sensor data. (For example, urdf has `sensor name` item, but sdf does not.)
Same was happened when using sample files in test folder. 

We checked other sdf file such as icub model in icub-gazebo, and found that it has ft sensor data with plugin information. 

Should we manually write the sensor information in sdf file, or are there some tips about creating urdf file or converting it to sdf file?

**Comment by kzts** [comment]
`simmechanics-to-urdf/test/test.urdf` inculdes the following setences
```
  <joint name="r_leg_ft_sensor" type="fixed">
...
  </joint>

```
We made this urdf file from files in `simmechanics-to-urdf/test/`.
But a sdf file we made from this urdf file doesn't include this joint `r_leg_ft_sensor`.
We made it commanding following.
```
gz sdf -p test.urdf > test.sdf
```
Is there anything wrong in our procedure?
Can we use FT sensors using this sdf file without joint `r_leg_ft_sensor`?
@iron76 @traversaro

**Comment by traversaro** [comment]
Sorry for the late reply! 

Basically the default behaviour of Gazebo for fixed joints in URDF is to remove them, by "fusing" the two links that they connect. The workaround that we used when we did the iCub model was to manually convert the URDF fixed joint to a revolute joint with limits of 0,0 . 

However since Gazebo 5 (or 6, I don't remember) [1] this can be done automatically by the URDF --> SDF converter using the `disableFixedJointLumping` option in the gazebo extension of the URDF, you can see an example of its use in:
https://github.com/robotology-playground/icub-gazebo/blob/60aeebe7690515b2a1e4ba85f0c0689375fbb902/iCubGenova02/iCubGenova02_simmechanics_options.yaml#L361

[1] : https://bitbucket.org/osrf/sdformat/pull-requests/133/added-urdf-gazebo-extension-option-to/diff

**Comment by kzts** [comment]
@traversaro Thnk you for your reply! I changed some files manually and I made the sdf file including ft sensors.
